### ISSUE TITLE
Is there a way to have the not obfuscated paella-core code while testing this repo?

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-user-tracking#2]
Hi, 

I'm programming a new plugin that should be here. During the debug I've found that the paella-core code is obfuscated (I think is that because it retrieves the npm from the internet), Is there a way to not get the obfuscated code instead?

Or it is more simple to code using the paella-core repo and later, when the plugin is finished push it to this repo?

**Comment by ferserc1** [comment]
I advise you to check the configuration of your project. All repositories, both paella-core and its plugins, include in their distribution the sourcemap files, which work without problems. 

I attach some screenshots. Specifically, these are from Paella Player 7 in Opencast, but you can try it in the [reference player](https://github.com/polimediaupv/paella-player), which also work without problems.

Note also, that depending on the browser you use, the source code from the sourcemaps usually appears in another part of the file tree. In the case of Firefox, it appears in the `Webpack` section.

![imagen](https://user-images.githubusercontent.com/7019720/153210946-4530f0d5-967a-45da-8d17-a4248f3a3f13.png)

![imagen](https://user-images.githubusercontent.com/7019720/153211291-44600a07-c219-4007-a69f-7a43a320cf19.png)
